### ISSUE TITLE
BUG - urn not accepted as IDs for submodels

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-aaspe/package-explorer#108]
**Describe the bug**
Creating a submodel with a Custom ID with urn (e.g. urn:bamm:com.bosch.nexeed.digitaltwin:1.0.0#Movement) is possible. However, after storing and re-open it there is an error that the submodel reference is missing (error: "Missing Submodel for Reference!)

urn makes sense for submodel templates.

**To Reproduce**
1. Create AAS
2. Create Submodel with identification urn:bamm:com.bosch.nexeed.digitaltwin:1.0.0#Movement
3. Store .aasx
4. open stored .aasx

**Expected behavior**
submodel shall be available as specified

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22]  Build date: Thu 01/20/2022

**Comments**
I tested it with older version (build time 02/25/2021): there is worked. So perhaps there are some checks now constraining it?

**Comment by BirgitBoss** [comment]
I tested it with v2024-06-10: there it is working

**Comment by juileetikekar** [comment]
As the functionality is working as expected in the latest version, closing this issue.
