### ISSUE TITLE
[BUG] empty <supplementalSemanticIds /> elements exported in XML

### ISSUE THREAD

**Issue by Christian-Block** [eclipse-aaspe/package-explorer#195]
Please see Issue [273](https://github.com/eclipse-aas4j/aas4j/issues/273) in AAS4J repository.

The XML generated by AASP creates empty `<supplementalSemanticIds />` elements.

supplementalSemanticIds is specified in IDTA 01001-3-0 and is included in [XSD](https://github.com/admin-shell-io/aas-specs/blob/2ab08f92bdd1d44edc1cfee52552fe5429d2178e/schemas/xml/AAS.xsd#L501). Both define supplementalSemanticIds  as optional.

However, it seems, that the AASP does not follow the XML [optional-properties](https://github.com/admin-shell-io/aas-specs/tree/master/schemas/xml#optional-properties) rule.

It seems to make a difference if you have created supplementalSemanticIds 
![image](https://github.com/eclipse-aaspe/aaspe/assets/48085349/22092959-615e-4820-87e7-a14fc198d024) (case 1)

or not
![image](https://github.com/eclipse-aaspe/aaspe/assets/48085349/c897a42a-419a-4dfd-a926-556a39b13e87) (case 2)

In case 1 an empty <supplementalSemanticIds /> element is not exported.
In case 2 an empty <supplementalSemanticIds /> element is exported.

Tested Version: v2024-02-27

**Comment by FrankSchnicke** [comment]
This does also happen with Qualifiers as well as with OperationVariables. With the latest update of AAS4J, it should be able to handle these AASX - but nevertheless, it would be better if this was fixed.

**Comment by sebastiankb** [comment]
fyi 

https://github.com/eclipse-aas4j/aas4j/issues/273#issuecomment-2049927567

**Comment by foprs** [comment]
Here is a further example of empty elements <description> in this case a Concept Description copied into the buffer from the AASPE. AASPE is generating these empty elements. In some cases, after deletion of an element, the empty element is left.

In this case the AAS API for ConceptDescriptions is refusing the JSON and the CD can't be imported into a CD Repository.

This is a major bug and should be adressed a.s.a.p.

![image](https://github.com/eclipse-aaspe/aaspe/assets/118162568/6e8b5f9c-b33c-4c05-bae9-97a68dce763a)

**Comment by mristin** [comment]
Just for reference. Here's the excerpt from https://github.com/admin-shell-io/aas-specs/tree/master/schemas/json#uml-properties-to-json-properties:

> Aggregations, i.e., the properties with the cardinality 0..*, 1..* etc., are modeled as [JSON arrays](https://json-schema.org/understanding-json-schema/reference/array.html).
>
> We explicitly forbid empty JSON arrays to avoid confusion about properties which have cardinality 0..*. Namely, an empty array is semantically equal to an omitted attribute (according to the meta-model). Thus, the JSON property representing an aggregation attribute must be omitted if the aggregation is empty.

**Comment by BirgitBoss** [comment]
see https://github.com/admin-shell-io/aas-specs/issues/418

**Comment by juileetikekar** [comment]
Hi @Christian-Block,

Thank you for raising the issue !

We have developed a new feature "Fix and Finalize" which removes/fixes the issue with empty lists and empty strings. In additional to this, we are also working on more hints in such violations.

Meanwhile, I would like to request you to use this "Fix and Finalize" option to remove empty <supplimentalSemanticIds/> or such optional strings/lists from the serialization.

<img width="164" alt="image" src="https://github.com/eclipse-aaspe/package-explorer/assets/99317579/e0383ed1-99bf-4de1-82a6-5a93bf8000c9">
