### ISSUE TITLE
No 'aasx-spec' document found in .aasx.

### ISSUE THREAD

**Issue by yucef428** [eclipse-aaspe/package-explorer#203]
When I try to pull a server from Docker Hub and implement my AASX, I get this error message: "No 'aasx-spec' document found in .aasx." 
![help](https://github.com/eclipse-basyx/basyx-applications/assets/168128784/320f2e52-3097-43c2-b557-c56ff7614bbf)

**Comment by juileetikekar** [comment]
Hi @yucef428,

Could you please provide more description to the issue?

Which components/tools are being used? If possible, could you also share the AASX File you are using?

**Comment by yucef428** [comment]
hi @juileetikekar 
I'm trying to connect my AAS to the server from Docker Hub using "eclipsebasyx/aas-server," but when I use my file, I have the error line shared befor .
https://drive.google.com/drive/folders/1K7YWcSfvW2i8q74RJwkr_YsdWUtSq7En?usp=sharing this is the aas used

**Comment by juileetikekar** [comment]
Hi @yucef428,

Thank you for sharing the inputs.

I checked the AASX file and it looks fine for me. 

If the exception in BaSyx with "aasx-spec" refers to the relationship type, then as per my understanding the check should be for "aas-spec" instead of "aasx-spec".
@FrankSchnicke Could you please check if the issue lies in BaSyx?

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/2e11735c-173a-4017-8783-9348d2d60cb0)

**Comment by FrankSchnicke** [comment]
This is already being discussed here: https://github.com/eclipse-basyx/basyx-applications/issues/124

The underlying issue is most likely using a V3 AAS with BaSyx V1.

**Comment by yucef428** [comment]
@FrankSchnicke  Hello again, I was using V1  (AAS), and everything was working well for 3 days. However, now I have a connection problem with the server.
![image](https://github.com/eclipse-aaspe/package-explorer/assets/168128784/1c2ba86b-09c2-41eb-8e0c-33623ee4e980)
![image](https://github.com/eclipse-aaspe/package-explorer/assets/168128784/7f34f38f-b200-420e-9ed2-dce5ccf7f27b)

**Comment by yucef428** [comment]
![image](https://github.com/eclipse-aaspe/package-explorer/assets/168128784/deb9a754-1e61-4a4d-804f-a356b533796d)
Just to add this error
