### ISSUE TITLE
Add ability to delete optional string values

### ISSUE THREAD

**Issue by pjaydev** [eclipse-aaspe/package-explorer#221]
According to the spec, the `idShort` attribute is an optional attribute for submodel elements. Nevertheless, after an `idShort` value has once been set, it can no longer be deleted. When just blanking the input field, still an empty string value will be stored for the `idShort` property on the generated JSON output.

In my use case, this caused two specific problems:
- As specified in *Constraint AASd-120*, elements, which are used as direct child of `SubmodelElementList` shall **not**  have set an `idShort`. If an idShort was accidentally set, you will have to delete the whole element (tree) to restore conformity.
- The [OpenAPI implemenetation](https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/Identifiable) requires a minimum of **1 character** for `idShort`, if the field is defined. Hence the schema validator refuses a SubmodelElement object containing an `idShort` attribute with an empty string as value, as generated by the PackageExplorer.

*EDIT:* In fact the described problem does not only relate to  `ìdShort` attributes, but rather more to each optional string-typed attribute you can find within the AAS schema. Further examples are all three string fields `version`, `revision` and `templateId` in the `Submodel.administration` field or the `value` attribute of a `Property` and possibly there are many more. I adjusted the issue title accordingly.

Thanks in advance.

**Comment by juileetikekar** [comment]
Hi @pjaydev,

Thank you for raising the issue !

We have developed a new feature "Fix and Finalize" which removes/fixes the issue with empty lists and empty strings. In additional to this, we are also working on more hints in such violations.

Meanwhile, I would like to request you to use this "Fix and Finalize" option to remove empty idShorts or such optional strings from the serialization.

<img width="170" alt="image" src="https://github.com/eclipse-aaspe/package-explorer/assets/99317579/95ca9e51-06c7-4840-bda0-5211db1f1c0e">
