### ISSUE TITLE
[BUG] isShort is not required for Identifiables (AAS, Submodel, Concept Description)

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-aaspe/package-explorer#223]
**Describe the bug**
When creating a new AAS, a new Concept Description or a new Submodel the idShort is always required (and leads to a corresponding "SpecViolation" in "Check, validate and fix" if not set)

**Expected behavior**
If the editor of the AASX does not add a idShort for an Identifiable then the corresponding property should not part of the serialization from the very beginning.

**Explorer Version**

  Version v2024-06-10

see also https://github.com/eclipse-aaspe/package-explorer/issues/221

**Comment by juileetikekar** [comment]
Hi @BirgitBoss,

Thank you for raising the issue !

We have developed a new feature "Fix and Finalize" which removes/fixes the issue with empty lists and empty strings. In additiona to this, we are also working on more hints in such violations.

Meanwhile, I would like to request you to use this "Fix and Finalize" option to remove empty idShorts of Identifiables from the serialization.

<img width="172" alt="image" src="https://github.com/eclipse-aaspe/package-explorer/assets/99317579/f52bf52d-6d70-4324-aecf-6b3cd456cc0d">
