### ISSUE TITLE
[BUG] i can find the exe file to open the aasx packageexplorer user interface

### ISSUE THREAD

**Issue by KarimElsemary** [eclipse-aaspe/package-explorer#229]
i can find the exe file to open the aasx packageexplorer user interface. so if any one can help me out. or if there a preperation steps or tools my be made  please let me know.

**Comment by juileetikekar** [comment]
Hi @KarimElsemary,

You can find the executables at below path, for instance
\aasx-package-explorer.LATEST.alpha.2024-07-04T08-10-03Z\aasx-package-explorer\AasxPackageExplorer

![image](https://github.com/user-attachments/assets/c510c766-7cb6-4b84-9279-1ef6e7498a00)
