### ISSUE TITLE
[BUG] Spelling mistake for 'value'-hint in IEC61360 Data Specification 

### ISSUE THREAD

**Issue by Gnadi27** [eclipse-aaspe/package-explorer#250]
When creating a IEC61360 Data Specification for a Property the hint for the 'value' has two spelling mistake by spelling out "If the ** *concepts stands* ** for a single ** *vlaue* **, please provide the value. Not required for enumerations or properties."
![grafik](https://github.com/user-attachments/assets/cffa7d97-7fab-46f9-8e58-9d3edc7cc4f5)

**Comment by juileetikekar** [comment]
Hi @Gnadi27,

The issue has been fixed and will be part of new release.

![image](https://github.com/user-attachments/assets/e3c92be5-c550-4040-b452-b57d2405db71)
